version: '3'

services: 
    app:
        build: 
            context: ./app
        container_name: app
        networks: 
            - node-network
        volumes: 
            - ./app/:/usr/src/app
        tty: true
        ports: 
            - "3000:3000"
        depends_on: 
            - db

    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        networks: 
            - node-network
        ports:
            - "8080:80"

    db:
        build: 
            context: ./mysql
            dockerfile: Dockerfile
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./mysql/data:/var/lib/mysql
        networks: 
            - node-network

networks: 
    node-network:
        driver: bridge